// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNEYZu1rVAsSs73mlQR1vxDhQxNbOOOFc',
    appId: '1:272804287975:web:0b9e9f0c5220813dd05942',
    messagingSenderId: '272804287975',
    projectId: 'heal-tracker-b24f2',
    authDomain: 'heal-tracker-b24f2.firebaseapp.com',
    storageBucket: 'heal-tracker-b24f2.firebasestorage.app',
    measurementId: 'G-YP9JQ8ER1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0MHQQsjFgUds5lqtuyoc9QU483VEQ1P8',
    appId: '1:272804287975:android:364264738d428569d05942',
    messagingSenderId: '272804287975',
    projectId: 'heal-tracker-b24f2',
    storageBucket: 'heal-tracker-b24f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUngHizaUpYnDXZ7CtaU_mj_ymjGXwx0',
    appId: '1:272804287975:ios:4bf8f02baea6e975d05942',
    messagingSenderId: '272804287975',
    projectId: 'heal-tracker-b24f2',
    storageBucket: 'heal-tracker-b24f2.firebasestorage.app',
    iosClientId: '272804287975-flgmoc0ohcmamot7sl5vtpa096die7d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.healtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUngHizaUpYnDXZ7CtaU_mj_ymjGXwx0',
    appId: '1:272804287975:ios:4bf8f02baea6e975d05942',
    messagingSenderId: '272804287975',
    projectId: 'heal-tracker-b24f2',
    storageBucket: 'heal-tracker-b24f2.firebasestorage.app',
    iosClientId: '272804287975-flgmoc0ohcmamot7sl5vtpa096die7d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.healtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNEYZu1rVAsSs73mlQR1vxDhQxNbOOOFc',
    appId: '1:272804287975:web:cf90a917bf68e6bbd05942',
    messagingSenderId: '272804287975',
    projectId: 'heal-tracker-b24f2',
    authDomain: 'heal-tracker-b24f2.firebaseapp.com',
    storageBucket: 'heal-tracker-b24f2.firebasestorage.app',
    measurementId: 'G-F450F89QXK',
  );

}